<?php
/**
 * Blue Motors Southampton Autoloader
 * Auto-generated by Comprehensive Plugin Fixer
 */

if (!function_exists('bms_autoloader')) {
    function bms_autoloader($class_name) {
        // Only handle our namespace
        if (strpos($class_name, 'BlueMotosSouthampton\\') !== 0) {
            return;
        }
        
        // Remove namespace prefix
        $class_name = str_replace('BlueMotosSouthampton\\', '', $class_name);
        
        // Convert namespace separators to directory separators
        $class_name = str_replace('\\', '/', $class_name);
        
        // Map to file paths
        $class_mappings = [
            'Services/CacheManager' => 'includes/services/class-cache-manager.php',
            'Services/ServiceManager' => 'includes/services/class-service-manager.php',
            'Services/ServiceManagerEnhanced' => 'includes/services/class-service-manager-enhanced.php',
            'Services/PricingCalculator' => 'includes/services/class-pricing-calculator.php',
            'Services/PricingCalculatorEnhanced' => 'includes/services/class-pricing-calculator.php',
            'Services/TyreService' => 'includes/services/class-tyre-service.php',
            'Services/VehicleLookupEnhanced' => 'includes/services/class-vehicle-lookup-enhanced.php',
            'Services/EmailManager' => 'includes/services/class-email-manager.php',
            'Utils/Session' => 'includes/class-bms-session.php',
        ];
        
        if (isset($class_mappings[$class_name])) {
            $file_path = BMS_PLUGIN_DIR . $class_mappings[$class_name];
            if (file_exists($file_path)) {
                require_once $file_path;
            }
        }
    }
    
    spl_autoload_register('bms_autoloader');
}
